// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl20gTfb3_qvOFcOzb49HFVkBZvr2PpaQ',
    appId: '1:941720131416:web:4dbb9ba50ba858c660772d',
    messagingSenderId: '941720131416',
    projectId: 'enrichmentquizapp',
    authDomain: 'enrichmentquizapp.firebaseapp.com',
    storageBucket: 'enrichmentquizapp.appspot.com',
    measurementId: 'G-J30E9R2QB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyfYaHkU9-trDt7pWBrI3vPvgLbl57AmQ',
    appId: '1:941720131416:android:244ae946be78242c60772d',
    messagingSenderId: '941720131416',
    projectId: 'enrichmentquizapp',
    storageBucket: 'enrichmentquizapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyrS6rkKwq4xBOkU-38-22okPn41DgU6w',
    appId: '1:941720131416:ios:b5fc00330f81575c60772d',
    messagingSenderId: '941720131416',
    projectId: 'enrichmentquizapp',
    storageBucket: 'enrichmentquizapp.appspot.com',
    iosBundleId: 'com.example.quizAppEnrichment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyrS6rkKwq4xBOkU-38-22okPn41DgU6w',
    appId: '1:941720131416:ios:b5fc00330f81575c60772d',
    messagingSenderId: '941720131416',
    projectId: 'enrichmentquizapp',
    storageBucket: 'enrichmentquizapp.appspot.com',
    iosBundleId: 'com.example.quizAppEnrichment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl20gTfb3_qvOFcOzb49HFVkBZvr2PpaQ',
    appId: '1:941720131416:web:04fd020808162ac060772d',
    messagingSenderId: '941720131416',
    projectId: 'enrichmentquizapp',
    authDomain: 'enrichmentquizapp.firebaseapp.com',
    storageBucket: 'enrichmentquizapp.appspot.com',
    measurementId: 'G-5BT6GB5WGK',
  );
}
